server:
  port: 8080
  forward-headers-strategy: framework

spring:
  security:
    jwt:
      secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5NzY0NjIxMSwiaWF0IjoxNjk3NjQ2MjExfQ.aJJTADa3j3BR2xHjC4DcRfj50Cv4Gr5v4-sot39e2Sk
      access.lifetime: 1  # days

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5430}/${DB_NAME:CTF}?createIfNotExists=true
    username: user
    password: password

  jpa:
    show-sql: true
    format-sql: true
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none

values:
  baseUrl: 127.0.0.1:8080